### ISSUE TITLE
Configuration test script

### ISSUE THREAD

**Issue by o1da** [klokantech/nginx-docker#1]
We should add script which checks nginx configuration (`nginx -t`) into docker image. Production logic should looks like:
- ansible pushes changed configuration to remote host
- ansible triggers test script
- if configuration is OK, process continues to docker image restart (via docker-deploy)
- if configuration is NOT OK, process stops there and none of docker images is being restarted

@keosak please check this issue description if it makes sense to you.

**Comment by keosak** [comment]
In https://github.com/klokan/deploy/blob/master/roles/nginx/handlers/main.yml.
